<a href="https://colab.research.google.com/github/pkaviyapkaviya609-dotcom/ml2/blob/main/ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv('/content/heart_disease_dataset.csv')
df

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease
0,75,Female,228,119,66,Current,Heavy,1,No,No,Yes,8,119,Yes,Atypical Angina,1
1,48,Male,204,165,62,Current,NaN,5,No,No,No,9,70,Yes,Typical Angina,0
2,53,Male,234,91,67,Never,Heavy,3,Yes,No,Yes,5,196,Yes,Atypical Angina,1
3,69,Female,192,90,72,Current,NaN,4,No,Yes,No,7,107,Yes,Non-anginal Pain,0
4,62,Female,172,163,93,Never,NaN,6,No,Yes,No,2,183,Yes,Asymptomatic,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,56,Female,269,111,86,Never,Heavy,5,No,Yes,Yes,10,120,No,Non-anginal Pain,1
996,78,Female,334,145,76,Never,NaN,6,No,No,No,10,196,Yes,Typical Angina,1
997,79,Male,151,179,81,Never,Moderate,4,Yes,No,Yes,8,189,Yes,Asymptomatic,0
998,60,Female,326,151,68,Former,NaN,8,Yes,Yes,No,5,174,Yes,Atypical Angina,1
999,53,Male,226,116,82,Current,NaN,6,No,No,Yes,5,161,Yes,Asymptomatic,1

In [ ]:
df.columns

Index(['Age', 'Gender', 'Cholesterol', 'Blood Pressure', 'Heart Rate',
       'Smoking', 'Alcohol Intake', 'Exercise Hours', 'Family History',
       'Diabetes', 'Obesity', 'Stress Level', 'Blood Sugar',
       'Exercise Induced Angina', 'Chest Pain Type', 'Heart Disease'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1000 non-null   int64
 1   Gender                   1000 non-null   object
 2   Cholesterol              1000 non-null   int64
 3   Blood Pressure           1000 non-null   int64
 4   Heart Rate               1000 non-null   int64
 5   Smoking                  1000 non-null   object
 6   Alcohol Intake           660 non-null    object
 7   Exercise Hours           1000 non-null   int64
 8   Family History           1000 non-null   object
 9   Diabetes                 1000 non-null   object
 10  Obesity                  1000 non-null   object
 11  Stress Level             1000 non-null   int64
 12  Blood Sugar              1000 non-null   int64
 13  Exercise Induced Angina  1000 non-null   object
 14  Chest Pain Type          1000 non-null   object
 15  Heart Disease            1000 non-null   int64
dtypes: int64(8), object(8)
memory usage: 125.1+ KB

In [ ]:
df.shape

(1000, 16)

In [ ]:
df.isnull().sum()

Age                          0
Gender                       0
Cholesterol                  0
Blood Pressure               0
Heart Rate                   0
Smoking                      0
Alcohol Intake             340
Exercise Hours               0
Family History               0
Diabetes                     0
Obesity                      0
Stress Level                 0
Blood Sugar                  0
Exercise Induced Angina      0
Chest Pain Type              0
Heart Disease                0
dtype: int64

In [ ]:
df.dropna()

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease
0,75,Female,228,119,66,Current,Heavy,1,No,No,Yes,8,119,Yes,Atypical Angina,1
2,53,Male,234,91,67,Never,Heavy,3,Yes,No,Yes,5,196,Yes,Atypical Angina,1
6,64,Female,211,105,86,Former,Heavy,8,Yes,Yes,Yes,2,120,No,Typical Angina,1
7,60,Female,208,148,83,Never,Moderate,4,No,Yes,Yes,2,113,Yes,Asymptomatic,1
8,37,Female,317,137,66,Current,Heavy,3,No,Yes,Yes,5,114,No,Non-anginal Pain,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,26,Female,215,100,74,Never,Heavy,7,No,Yes,No,10,135,No,Atypical Angina,0
992,28,Female,220,102,73,Current,Moderate,7,Yes,Yes,Yes,10,102,No,Typical Angina,0
994,52,Male,248,159,76,Former,Moderate,9,No,Yes,Yes,2,152,Yes,Asymptomatic,1
995,56,Female,269,111,86,Never,Heavy,5,No,Yes,Yes,10,120,No,Non-anginal Pain,1
997,79,Male,151,179,81,Never,Moderate,4,Yes,No,Yes,8,189,Yes,Asymptomatic,0

In [ ]:
df.fillna(method='ffill',inplace=True)

/tmp/ipython-input-4116506308.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',inplace=True)

In [ ]:
x=df[['Age', 'Gender', 'Cholesterol', 'Blood Pressure', 'Heart Rate',
       'Smoking', 'Alcohol Intake', 'Exercise Hours', 'Family History',
       'Diabetes', 'Obesity', 'Stress Level', 'Blood Sugar']]
x

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar
0,75,Female,228,119,66,Current,Heavy,1,No,No,Yes,8,119
1,48,Male,204,165,62,Current,Heavy,5,No,No,No,9,70
2,53,Male,234,91,67,Never,Heavy,3,Yes,No,Yes,5,196
3,69,Female,192,90,72,Current,Heavy,4,No,Yes,No,7,107
4,62,Female,172,163,93,Never,Heavy,6,No,Yes,No,2,183
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,56,Female,269,111,86,Never,Heavy,5,No,Yes,Yes,10,120
996,78,Female,334,145,76,Never,Heavy,6,No,No,No,10,196
997,79,Male,151,179,81,Never,Moderate,4,Yes,No,Yes,8,189
998,60,Female,326,151,68,Former,Moderate,8,Yes,Yes,No,5,174
999,53,Male,226,116,82,Current,Moderate,6,No,No,Yes,5,161

In [ ]:
y=df[['Heart Disease']]
y

     Heart Disease
0                1
1                0
2                1
3                0
4                0
..             ...
995              1
996              1
997              0
998              1
999              1

[1000 rows x 1 columns]

In [ ]:
import pandas as pd
x=df.iloc[:,:-1]
x = pd.get_dummies(x, drop_first=True) # Apply one-hot encoding to categorical features
x

,Age,Cholesterol,Blood Pressure,Heart Rate,Exercise Hours,Stress Level,Blood Sugar,Gender_Male,Smoking_Former,Smoking_Never,Alcohol Intake_Moderate,Family History_Yes,Diabetes_Yes,Obesity_Yes,Exercise Induced Angina_Yes,Chest Pain Type_Atypical Angina,Chest Pain Type_Non-anginal Pain,Chest Pain Type_Typical Angina
0,75,228,119,66,1,8,119,False,False,False,False,False,False,True,True,True,False,False
1,48,204,165,62,5,9,70,True,False,False,False,False,False,False,True,False,False,True
2,53,234,91,67,3,5,196,True,False,True,False,True,False,True,True,True,False,False
3,69,192,90,72,4,7,107,False,False,False,False,False,True,False,True,False,True,False
4,62,172,163,93,6,2,183,False,False,True,False,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,56,269,111,86,5,10,120,False,False,True,False,False,True,True,False,False,True,False
996,78,334,145,76,6,10,196,False,False,True,False,False,False,False,True,False,False,True
997,79,151,179,81,4,8,189,True,False,True,True,True,False,True,True,False,False,False
998,60,326,151,68,8,5,174,False,True,False,True,True,True,False,True,True,False,False
999,53,226,116,82,6,5,161,True,False,False,True,False,False,True,True,False,False,False

In [ ]:
y=df.iloc[:,-1]
y

0      1
1      0
2      1
3      0
4      0
      ..
995    1
996    1
997    0
998    1
999    1
Name: Heart Disease, Length: 1000, dtype: int64

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Redefine x and y to ensure they are up-to-date and correctly preprocessed
x = df.iloc[:,:-1]
x = pd.get_dummies(x, drop_first=True) # Apply one-hot encoding to categorical features
y = df.iloc[:,-1]

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42) # Added random_state for reproducibility

In [ ]:
xtrain.shape

(800, 15)

In [ ]:
xtest.shape

(200, 15)

In [ ]:
ytrain.shape

(800,)

In [ ]:
ytest.shape

(200,)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

clf = RandomForestClassifier(random_state=42)
clf.fit(xtrain, ytrain)

ypred = clf.predict(xtest)

accuracy = accuracy_score(ytest, ypred)
print(accuracy)

1.0

In [ ]:
import pickle
with open('model.pkl', 'wb') as file:
    pickle.dump(clf, file)